Handle null properties
unicredit/sbt-swagger-codegen pull request #32
Opened 2016-11-29 07:51 UTC by devkat

* Avoid NPE in collection conversion when model.getProperties() returns null.
* Use case objects instead of case classes when parameter list is empty.

2016-11-29 12:49 UTC, andreaTP requested changes

2016-11-29 12:49 UTC, andreaTP commented on lib/src/main/scala/eu/unicredit/swagger/generators/DefaultModelGenerator.scala
> +        OBJECTDEF(GenClass) withFlags Flags.CASE
that is good indeed!

2016-11-29 12:49 UTC, andreaTP commented on build.sbt
> +      "com.google.guava" % "guava" % "20.0",
guava is not needed

2016-11-29 12:49 UTC, andreaTP commented on build.sbt
> +      "org.scalactic" %% "scalactic" % "3.0.1",
scalactic is not yet used

2016-11-29 12:49 UTC, andreaTP commented on lib/src/test/scala/eu/unicredit/swagger/ScalaUtilsSpec.scala
> +class ScalaUtilsSpec extends FlatSpec {
We really need some testing, thanks a lot for starting this :-)

2016-11-29 12:49 UTC, andreaTP commented
thanks a lot for this contribution.

2016-11-30 15:25 UTC, devkat commented on build.sbt
> +      "com.google.guava" % "guava" % "20.0",
It is used in ScalaUtils for the case format conversion.

2016-11-30 15:38 UTC, devkat commented on build.sbt
> +      "com.google.guava" % "guava" % "20.0",
Never mind, I saw that it is already included transitively.

2016-11-30 16:06 UTC, andreaTP commented
LGTM
Great, can you squash commits please? and than I will merge!

2016-12-21 11:00 UTC, fralken commented
Hello, this is a nice improvement, thanks! But there are still some problems. It is nice to have names converted to Scala identifiers, but right now this works only for the model. Both client and server generated code is broken, because it uses unconverted names. Have you time to check this?

btw, the last commit is broken (it contains unmerged code).

Anyway, thanks for this pr!

2016-12-21 11:58 UTC, devkat commented
Thanks for reviewing the PR. Unfortunately we have cancelled the project in question and I cannot invest any more time. Feel free to use any of the code changes.

2016-12-21 11:58 UTC, closed without merging

2016-12-22 08:26 UTC, fralken commented
Ok, I cherry picked some of your commits. Thanks anyway.